- name: compile coffeescript
  docker_container:
    name: "npm"
    image: quay.io/whathood/nodejs-bower-grunt
    volumes:
    - "{{ wh_src_dir }}:/data"
    cleanup: yes
    entrypoint: grunt coffee
  tags: [ coffee ]
  register: result
  become: yes
