#!/bin/bash

# instructions from: http://docs.pgrouting.org/2.0/en/doc/src/installation/index.html#ubuntu-debian

# Add pgRouting launchpad repository ("stable" or "unstable")
sudo add-apt-repository ppa:georepublic/pgrouting-unstable
sudo apt-get update

# Install pgRouting packages
sudo apt-get install postgresql-9.3-pgrouting -y
