---

- hosts: development
  vars:
    user: "{{ ansible_ssh_user }}"
    log_dir: /var/log/whathood
  roles:
    - { role: common, sudo: yes }
    - { role: virt_host_docker,
        sudo: yes,
        vars: { user: user },
        docker_group_members: [ user ]
      }
    - { role: vim, sudo: yes }
    - { role: rvm, sudo: yes }
    - { role: setup }
    - { role: docker_setup, sudo: yes }

- include: deploy.yml

- include: import_db.yml
  vars:
    nginx_container: "nginx-{{ application_env }}"

- hosts: development
  vars:
    user: "{{ ansible_ssh_user }}"
    log_dir: /var/log/whathood
  roles:
    - { role: import_db }
