---

- docker:
    name: wh-postgis
    image: quay.io/whathood/docker-postgis
    state: started

- docker:
    name: wh_memcached
    image: quay.io/whathood/docker-postgis
    state: started

- docker:
    name: "{{ container_name }}"
    image: "{{ docker_nginx_img }}"
    state: absent

- file: path=/var/log/whathood state=directory mode=0777

- file: path=/var/log/whathood/php-zend.log mode=0777

- name: relaunch the nginx container
  command: docker run --detach -v "/var/log/whathood:/var/log/whathood:rw" -v "{{ app_dir }}:/var/www/whathood:rw" -p "{{ http_port }}:80" --link wh-postgis:wh-postgis --link wh_memcached:wh_memcached -e 'PGPORT=5432' -e 'PGUSER=docker' -e 'PGHOST=wh-postgis' --name {{container_name}} {{ docker_nginx_img }}
  sudo: yes
