- name: make sure .npm directory is owned by ansible_user
  file: path=/home/{{ ansible_user }}/.npm state=directory owner={{ ansible_user }} recurse=yes mode="0777"
  become: yes

- name: make sure node_modules is owned by user
  file: path={{ wh_src_dir }}/node_modules state=directory recurse=yes owner={{ ansible_user }} mode="0777"
  become: yes

- name: npm install "{{item.name}}"
  npm:
    name: "{{item.name}}"
    path: "{{ wh_src_dir }}"
  with_items: "{{npm_modules}}"
