---
language: python
python: '2.7'
sudo: required

# disable the default submodule logic
git:
  submodules: false

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

  # from https://gist.github.com/petrbel/c3bf7e0f59c22a52f534
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

  - pip install ansible
  - pip install boto==2.46.1

install:
  # we're storing the decrypt pass as a travis env var ANSIBLE_VAULT_PASS
  - echo $ANSIBLE_VAULT_PASS > ${TRAVIS_BUILD_DIR}/vpass

  - openssl aes-256-cbc -K $encrypted_001ab3e66bfe_key -iv $encrypted_001ab3e66bfe_iv -in ansible/tests/id_rsa_ec2_tests.enc -out $PRIV_KEY -d

  - ansible-galaxy install -r ansible/requirements.yml -p ansible/roles

  - chmod 600 $PRIV_KEY

script:
  - echo $TRAVIS_BUILD_DIR
  # NO connection=local
  - ansible-playbook ansible/plays/provision_ec2.yml -e application_env=travis -e ansible_ssh_private_key_file=$PRIV_KEY

env:
  - PRIV_KEY=$TRAVIS_BUILD_DIR/ansible/tests/id_rsa_ec2_tests
