---
language: python
python: "2.7"

addons:
  ssh_known_hosts:
  - bitbucket.org

# disable the default submodule logic
git:
  submodules: false

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

  # from https://gist.github.com/petrbel/c3bf7e0f59c22a52f534
  - sed -i 's/git@bitbucket.org:/https:\/\/bitbucket.org\//' .gitmodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  # Install Ansible.
  - pip install ansible

script:
  - ansible-playbook ansible/provision_ec2.yml --syntax-check
