version: '3'

services:

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - "9200:9200"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.8.2
  #   ports:
  #     - "5601:5601"

  # postgres:
  #   image: quay.io/whathood/postgres
  #   ports:
  #     - "5432:5432"

  # memcached:
  #   image: quay.io/whathood/memcached
  #   ports:
  #     - "11211:11211"

  php-fpm:
    image: php:5.6-fpm
    volumes:
      - ${APP_DIR}/app:/code

  nginx:
    image: nginx:1.17.3
    ports:
      - "3000:80"
    volumes:
      - ${APP_DIR}/app/public:/code
      - ./docker/nginx/whathood-site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
