  - name: Set timezone variables
    copy: content='America/New_York'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
    notify:
    - update timezone
