# override whathood.yaml keys here
google_ui: {{ google_ui }}
email:
  smtpHost: {{ email_smtp_host }} 
  smtpPort: {{ email_smtp_port }}
  smtpUser: {{ email_smtp_user }}
  smtpPass: {{ email_smtp_pass }}
  fromAddress: {{ email_from_address }}
  toAddress: {{ email_to_address }}

