---

- hosts: all
  gather_facts: false
  tasks:
  - name: Setting whathood env var
    command: /bin/bash -c "echo 'WH_APP_ENV={{ item }}' >> /etc/environment"
    become: yes
    with_items: application_env

- hosts: all
  gather_facts: false
  vars:
    user: "{{ ansible_ssh_user }}"
  vars_files:
  - ../group_vars/npm_modules.yml
  roles:
    - role: whathood.clone_repo
    - role: whathood.npm_setup
      tags: [ npm_install, npm_setup ]
    - role: whathood.compile_coffeescript
      tags: compile_coffeescript

- hosts: all
  gather_facts: false
  tasks:

  - name: make sure the doctrine proxy dir is writeable
    file: path={{ wh_src_dir }}/app/data/DoctrineORMModule/Proxy mode=777 owner={{ansible_ssh_user}} state=directory
    become: yes

  - name: set applicaton_env
    lineinfile:
      dest: "{{wh_src_dir}}/application_env"
      line: "{{application_env}}"
      create: yes

- hosts: all
  gather_facts: true
  tasks:
  - name: install project ruby gems
    command: /home/ubuntu/.rvm/gems/ruby-2.3.1/wrappers/bundle install
    environment:
      PATH: "/home/ubuntu/.rvm:{{ ansible_env.PATH }}"
    args:
      chdir: "{{wh_src_dir}}"
    tags: [ ruby, ruby-bundle ]

- hosts: all
  gather_facts: false
  roles:
    - role: whathood.grunt_uglify
      tags: grunt_uglify
