---
# deploy.yml
#
# should:
# * prepare the docker environment
# * call the compile play
#
- hosts: all
  gather_facts: false
  vars:
    user: "{{ ansible_ssh_user }}"
    wh_log_dir: /var/log/whathood
  roles:
    - role: whathood.prep_docker_env
      tags: prep_docker_env 

    - role: whathood.hostname_set
      tags: hostname_set

    - role: whathood.prep_log_dir
      tags: [ prep_log_dir ]

- hosts: all
  gather_facts: false
  vars:
    skip_db_check: true
  tasks:
  - name: touch php-zend.log
    file: path=/var/log/whathood/php-zend.log state=touch owner={{ansible_ssh_user}} mode=0777
    become: yes

  - name: make sure ssh-keyscan command works
    command: echo `ssh-keyscan github.com`
    become: yes

  - name: add github to known hosts
    command: echo `ssh-keyscan github.com` >> /root/.ssh/known_hosts
    become: yes

  # on setup, wh-foreman won't exist, so ignore errors
  - command: status wh-foreman
    register: result
    ignore_errors: yes

  - shell: stop wh-foreman
    become: yes
    when: '"started" in result.stdout'
    
  - command: status wh-worker
    register: result
    ignore_errors: yes

  - shell: stop wh-worker
    become: yes
    when: '"started" in result.stdout'

  - shell: docker stop wh-jsx || true
    become: yes
    when: (application_env is defined) and (application_env == 'development')

  - shell: docker rm -f wh-jsx || true
    become: yes
    when: (application_env is defined) and (application_env == 'development')

  - shell: docker start wh_memcached || true
    become: yes

  - name: checking database schema
    command: "{{ wh_src_dir }}/d-bin/check_db_schema"
    when: not skip_db_check

- include: compile.yml

- hosts: all
  gather_facts: false
  vars:
    user: "{{ ansible_ssh_user }}"
  roles:
    - role: composer
      tags: composer
    - role: less
      tags: less

    - bundler

    - { role: copy_code, from_dir: "{{ wh_src_dir }}", to_dir: "{{deploy_dest_dir}}" }

    - { role: "nginx", container_name: "nginx", http_port: "81", app_dir: "{{ wh_src_dir }}" }

    - role: update_upstart
      tags: update_upstart
      sudo: yes

    - role: system_check
      system_check_dir: "{{application_root}}"
      tags: system_check
