- hosts: all
  gather_facts: true
  vars:
    user: "{{ ansible_ssh_user }}"
    log_dir: /var/log/whathood
    dot_vim_dir: "/home/{{ansible_ssh_user}}/.vim"
  roles:
    - name: install common stuff on the guest
      role: common
      tags: common
      become: yes

    - name: configure vim
      role: jsmiley.vim
      tags: vim
