---

- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/vault.yml
    - group_vars/all.yml
  roles:
    - role: jsmiley.provision_ec2
  environment:
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_KEY: "{{ aws_secret_key }}"

- include: setup.yml hosts=localhost
