---
  
- name: install ruby, node and docker
  hosts: all
  gather_facts: true
  vars_files:
    - group_vars/vault.yml
  vars:
    user: "{{ ansible_user }}"
    log_dir: /var/log/whathood
  roles:

    - role: geerlingguy.nodejs
      become: yes
      vars:
        nodejs_version: "9.x"
      tags: node_install

    - role: rvm.ruby
      vars:
        rvm1_user: "{{ ansible_user }}"
        rvm1_rubies:
          - ruby-2.3.1
        rvm1_install_path: "/home/{{ ansible_user }}/.rvm"
      become: yes
      tags: ruby

    - role: git
      become: yes

    - role: geerlingguy.pip
      vars:
        pip_package: python3-pip
        pip_executable: pip3
        pip_install_packages:
          - docker
          - docker-compose
      become: yes
      tags: [ "docker" ]

    - role: geerlingguy.docker
      become: yes
      tags: [ "docker" ]

    - role: whathood.postgres
      tags: postgres

    # XXJIM - uncomment after travis build passes
    # - role: whathood.logentries_install
    #   tags: logentries_install
    #   become: yes

  post_tasks:

    - name: add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes
      register: group_add

    - name: reboot the VM to be able to use docker without sudo
      reboot:
      become: yes
      when: group_add.changed
