---

# ansible/plays/setup.yml

# run at the start in case you need to jump into the target and debug during ansible failures
- include: development_environment_setup.yml

- include: setup_guest.yml

- include: deploy.yml
  vars:
    skip_db_check: true
    skip_system_check: true

- hosts: all
  gather_facts: false
  vars:
    nginx_container: "{{nginx_container_name}}"
  roles:

  - role: whathood.import_db
    tags: import_db

  - role: whathood.system_check
    system_check_dir: "{{application_root}}"
    tags: system_check
