---

# setup should:
# * install base languages like ruby, node, npm # * it should then call deploy.yml
# * and then import the database
#
- hosts: all
  gather_facts: true
  vars:
    user: "{{ ansible_ssh_user }}"
    log_dir: /var/log/whathood
  roles:

    - role: nodesource.node
      become: yes
      tags: node_install

    - role: jsmiley.vim
      tags: vim

    - role: jsmiley.bash
      tags: bash

    - role: rvm_io.ruby
      tags: ruby
      rvm1_rubies: ['ruby-2.3.1']
      rvm1_user: 'ubuntu'
      become: yes

- include: git.yml

- hosts: all
  gather_facts: false
  vars:
    ansible_ssh_user: "{{ ansible_user }}"
  tags: [ "docker" ]
  roles:
    - role: angstwad.docker_ubuntu
      pip_version_docker_py: '1.10.6'
  become: yes

- hosts: production
  gather_facts: false
  roles:
    - role: whathood.logentries_install
      tags: logentries_install
  become: yes

- include: deploy.yml
  vars:
    skip_db_check: true
    skip_system_check: true

- hosts: all
  gather_facts: false
  roles:
  - { role: whathood.import_db }
  vars:
    nginx_container: "{{nginx_container_name}}"
  tags: import_db
