---

# run at the start in case you need to jump into the target and debug
- include: development_environment_setup.yml

- hosts: all
  gather_facts: true
  vars:
    user: "{{ ansible_user }}"
    log_dir: /var/log/whathood
    rvm1_user: "{{ ansible_user }}"
    rvm1_rubies:
      - 'ruby-2.2.5'
    rvm1_install_path: "/home/{{ ansible_user }}/.rvm"
  roles:

    - role: nodesource.node
      become: yes
      tags: node_install


    - role: rvm_io.ruby
      tags: ruby
      rvm1_rubies: ['ruby-2.3.1']
      become: yes

    - role: git
      become: yes

- hosts: all
  gather_facts: false
  vars_files:
    - group_vars/vault.yml
  tags: [ "docker" ]
  roles:
    - role: angstwad.docker_ubuntu
      pip_version_docker_py: '1.10.6'
      become: yes

    - role: whathood.logentries_install
      tags: logentries_install
      become: yes

    - role: whathood.postgres
      tags: postgres

- include: deploy.yml
  vars:
    skip_db_check: true
    skip_system_check: true

- hosts: all
  gather_facts: false
  vars:
    nginx_container: "{{nginx_container_name}}"
  roles:

  - role: whathood.import_db
    tags: import_db

  - role: whathood.system_check
    system_check_dir: "{{application_root}}"
    tags: system_check
