---
  
- name: install ruby and node
  hosts: all
  gather_facts: true
  vars:
    user: "{{ ansible_user }}"
    log_dir: /var/log/whathood
    rvm1_user: "{{ ansible_user }}"
    rvm1_rubies:
      - 'ruby-2.2.5'
    rvm1_install_path: "/home/{{ ansible_user }}/.rvm"
  roles:

    - role: geerlingguy.nodejs
      become: yes
      vars:
        nodejs_version: "9.x"
      tags: node_install


    - role: rvm.ruby
      tags: ruby
      rvm1_rubies: ['ruby-2.3.1']
      become: yes

    - role: git
      become: yes

- name: install docker
  hosts: all
  gather_facts: false
  vars_files:
    - group_vars/vault.yml
  tags: [ "docker" ]
  roles:
    - role: angstwad.docker_ubuntu
      pip_version_docker_py: '1.10.6'
      become: yes

    # XXJIM - uncomment after travis build passes
    # - role: whathood.logentries_install
    #   tags: logentries_install
    #   become: yes

    - role: whathood.postgres
      tags: postgres