---
# configure any docker images on the host

- file:
    path: /home/{{ansible_user}}/src
    state: directory
    owner: "{{ansible_user}}"
  become: yes

- name: Set  correct ssh key path
  set_fact:
    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file | realpath }}"

- synchronize:
    src: "{{ playbook_dir }}/../../docker"
    dest: /home/{{ansible_user}}/src/
    archive: yes
    recursive: yes
  remote_user: "{{ansible_user}}"

- include: composer.yml tags=composer
  become: yes

- name: memcached container is present
  docker_image:
    name: quay.io/whathood/memcached
    pull: yes
  become: yes

- name: image nginx is present
  docker_image:
    name: "{{docker_nginx_image}}"
    pull: yes
  become: yes

- name: memcached container is present
  docker_image:
    name: quay.io/whathood/postgres
    pull: yes
  become: yes

- template: src=wh-start-containers.conf.j2 dest=/etc/init/wh-start-containers.conf
  become: yes
