---

- name: find out if whathood source dir already exists
  stat: path={{ wh_src_dir }}/.git
  register: stat_result

- name: clone whathood repo
  git:
    force: yes
    repo: "{{ git_repo_url }}"
    dest: "{{ wh_src_dir }}"
    accept_hostkey: yes
  become: no
  when: not stat_result.stat.exists

- name: touch the log directory
  file: path=/var/log/whathood state=directory mode=0777
  become: yes

- name: copy template whathood.yml
  template: src=whathood.yml.j2 dest={{wh_src_dir}}/whathood.yml
