git_repo_url: https://github.com/whathood/whathood.git
rollbar_access_token: ""
google_ui: ""
email_smtp_host: ""
email_smtp_port: ""
email_smtp_pass: ""
email_from_address: ""
email_to_address: ""
email_smtp_user: ""
