---
# configure any docker images on the host

- file:
    path: /home/{{ansible_ssh_user}}/src
    state: directory
    owner: "{{ansible_ssh_user}}"

- synchronize:
    src: ../docker
    dest: /home/{{ansible_ssh_user}}/src/
    archive: yes
    recursive: yes
  remote_user: "{{ansible_ssh_user}}"

- name: image whathoood/jsx is present
  docker:
    name: wh_jsx
    image: quay.io/whathood/jsx
    state: present
  sudo: yes

- include: composer.yml tags=composer

- name: image whathood/grunt is present
  docker:
    name: wh_nodejs
    image: quay.io/whathood/nodejs-bower-grunt
    state: present
  sudo: yes

- name: memcached container is present
  docker:
    name: wh_memcached
    image: quay.io/whathood/memcached
    state: present
    restart_policy: always
  sudo: yes

- name: image nginx is present
  docker:
    name: nginx
    image: "{{docker_nginx_image}}"
    state: present
    restart_policy: always
  sudo: yes

- name: image whathood/postgres is present
  docker:
    name: wh-postgis
    image: quay.io/whathood/postgres
    state: present
    restart_policy: always
  sudo: yes

- include: docs.yml tags=phpdoc,docs sudo=yes
  when: application_env != "production"

- template: src=wh-start-containers.conf.j2 dest=/etc/init/wh-start-containers.conf
  sudo: yes
