---
# configure any docker images on the host

- file:
    path: /home/{{ansible_ssh_user}}/src
    state: directory
    owner: "{{ansible_ssh_user}}"
  become: yes

- name: Set  correct ssh key path
  set_fact: 
    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file | realpath }}"

- synchronize:
    src: ../docker
    dest: /home/{{ansible_ssh_user}}/src/
    archive: yes
    recursive: yes
  remote_user: "{{ansible_ssh_user}}"

- name: pip install docker
  pip: name=docker version=2.0.2
  become: yes

- name: pip install docker-py
  pip: name=docker-py version=1.9.0
  become: yes

- include: composer.yml tags=composer
  become: yes

- name: image whathood/grunt is present
  docker:
    name: wh_nodejs
    image: quay.io/whathood/nodejs-bower-grunt
    state: present
  become: yes

- name: memcached container is present
  docker:
    name: wh_memcached
    image: quay.io/whathood/memcached
    state: present
    restart_policy: always
  become: yes

- name: image nginx is present
  docker:
    name: nginx
    image: "{{docker_nginx_image}}"
    state: present
    restart_policy: always
  become: yes

- name: image whathood/postgres is present
  docker:
    name: wh-postgis
    image: quay.io/whathood/postgres
    state: present
    restart_policy: always
  become: yes

- include: docs.yml tags=phpdoc,docs sudo=yes
  when: application_env != "production"

- template: src=wh-start-containers.conf.j2 dest=/etc/init/wh-start-containers.conf
  become: yes
