---
# configure any docker images on the host

- name: image whathoood/jsx is present
  docker:
    name: wh_jsx
    image: quay.io/whathood/jsx
    state: present
  sudo: yes

- name: image whathood/composer is present
  docker:
    name: wh_composer
    image: quay.io/whathood/composer
    state: present
  sudo: yes

- name: image whathood/grunt is present
  docker:
    name: wh_nodejs
    image: quay.io/whathood/nodejs-bower-grunt
    state: present
  sudo: yes

- name: memcached container is present
  docker:
    name: wh_memcached
    image: quay.io/whathood/memcached
    state: present
    restart_policy: always
  sudo: yes

- name: image nginx is present
  docker:
    name: "NGINX_CONTAINER_NAME"
    image: "{{docker_nginx_image}}"
    state: present
    restart_policy: always
  sudo: yes

- name: image whathood/postgres is present
  docker:
    name: wh-postgis
    image: quay.io/whathood/postgres
    state: present
    restart_policy: always
  sudo: yes

- include: docs.yml tags=phpdoc,docs
