---

- name: ensure source dir files is owned by ansible_user
  file:
    path: "{{ wh_src_dir }}"
    owner: "{{ ansible_user }}"
    recurse: yes
  become: yes

- name: build whathood javascript
  shell: ./bin/grunt uglify
  args:
    chdir: "{{wh_src_dir}}"
