---

- file: path=/home/{{user}}/src state=directory mode=0755 owner={{user}} group={{user}}

- name: Clone whathood dev-ops
  git:
    repo=https://github.com/whathood/wh-devops.git dest=/home/{{user}}/src/wh-devops
