---

- name: Setting whathood env var
  command: echo "WH_APP_ENV={{application_env}}" >> /etc/environment
  sudo: yes

- name: clear deploy_working_dir
  shell: rm -rf {{ deploy_working_dir }} || true
  sudo: yes

   # need to cd into git_dir and clone from there because the dir will already exist
- name: clone whathood repo
  git: repo={{whathood_git_url}} dest="{{ deploy_working_dir }}"

- file: path=/var/log/whathood state=directory mode=0777
  sudo: yes

- name: touch php-zend.log
  file: path=/var/log/whathood/php-zend.log state=touch owner={{ansible_ssh_user}} mode=0777
  sudo: yes

- shell: stop wh-foreman || true
  sudo: yes

- shell: stop wh-worker || true
  sudo: yes

- shell: docker stop wh-jsx || true
  sudo: yes
  when: application_env == 'development'

- shell: docker rm -f wh-jsx || true
  sudo: yes
  when: application_env == 'development'

- shell: docker start wh_memcached || true
  sudo: yes

- name: checking database schema
  command: "{{ deploy_dir }}/d-bin/check_db_schema"
  when: not skip_db_check

  command: echo `ssh-keyscan github.com`
  sudo: yes

- name: add github to known hosts
  command: echo `ssh-keyscan github.com` >> /root/.ssh/known_hosts
  sudo: yes

- name: npm install dependencies
  command: docker run -it --rm -v {{ deploy_working_dir }}:/data quay.io/whathood/nodejs-bower-grunt npm install
  sudo: yes
  args:
    chdir: "{{ deploy_working_dir }}"

- name: compile coffeescript
  command: docker run -it --rm -v {{ deploy_working_dir }}:/data quay.io/whathood/nodejs-bower-grunt grunt coffee
  args:
    chdir: "{{ deploy_working_dir }}"
  sudo: yes

- file: path={{ deploy_working_dir }}/app/data/DoctrineORMModule/Proxy mode=777 owner={{ansible_ssh_user}} state=directory
  sudo: yes
 
- name: compile react
  command: docker run --rm -v {{ deploy_working_dir }}/libs/react:/src -v {{ deploy_working_dir }}/app/public/js/whathood:/build --name wh-jsx quay.io/whathood/jsx --extension jsx src build
  sudo: yes

- name: copy in whathood.yml
  template: src=whathood.yml.j2 dest={{deploy_working_dir}}/whathood.yml
