---

- name: set WH_NGINX_CONTAINER in environment
  command: /bin/bash -c "echo 'WH_NGINX_CONTAINER={{nginx_container_name}}' >> /etc/environment"
  become: yes


- name: memcached container is started
  docker:
    name: wh_memcached
    image: quay.io/whathood/memcached
    detach: true
    ports:
      - "11211:11211"
    state: started
  become: yes

- name: nginx PROD container is absent
  docker:
    name: nginx
    image: quay.io/whathood/nginx
    state: absent
  become: yes

- name: "{{ item.container_name }} nginx container is absent"
  docker:
    name: nginx
    image: "{{ docker_nginx_image }}"
    state: absent
  become: yes

- file: path=/var/log/whathood state=directory mode=0777

- file: path=/var/log/whathood/php-zend.log mode=0777

- name: run nginx container
  command: >
    docker run --detach
      -v "/var/log/whathood:/var/log/whathood:rw"
      -v "{{application_root}}:/var/www/whathood:rw"
      -p "{{docker_nginx_http_port}}:80"
      --link wh-postgis:wh-postgis
      --link wh_memcached:wh_memcached
      -e 'PGPORT=5432'
      -e 'PGUSER=docker'
      -e 'PGHOST=wh-postgis'
      --name nginx
      {{docker_nginx_image}} 
  become: yes
