---

- name: install pip dependencies
  apt: name={{ item }}
  with_items:
    - python-setuptools
    - python-dev
    - build-essential
    - urllib3
  become: yes

- name: check if pip is installed
  shell: "which pip"
  register: result
  ignore_errors: yes
  changed_when: (result.rc == 1)

- name: install pip
  shell: easy_install pip
  become: yes
  when: (result.rc == 1)

- name: install glances
  pip: name=glances
  become: yes
