---

- include: install_debian.yml
  when: ansible_os_family == 'Debian'
- include: install_redhat.yml
  when: ansible_os_family == 'RedHat'
- include: config.yml
- include: config_redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Bootstrap | Vim | Install pathogen for user '{{user}}' - download code
  command: curl -Sso /home/{{ user }}/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim creates=/home/$user/.vim/autoload/pathogen.vim

- name: Bootstrap | Vim | Push vimrc for user '{{user}}'
  template:
    src=vimrc
    dest=/home/{{user}}/.vimrc
    owner={{user}} group={{user}}

- name: Install vim-coffeescript
  git: repo=https://github.com/kchmck/vim-coffee-script.git dest=/home/{{ user }}/.vim/bundle/vim-coffee-script/

- name: Install vim-better-whitespace
  git: repo=https://github.com/ntpeters/vim-better-whitespace.git dest=/home/{{ user }}/.vim/bundle/vim-better-whitespace
