---

dist: trusty
sudo: required

language: python
python: '2.7'

cache: pip

install:

  # gotta sudo pip because docker will be sudo'd
  - sudo pip install -r ./requirements.txt
  - echo '[defaults]' > ansible.cfg
  - echo 'roles_path = ../:../../' >> ansible.cfg
  - echo 'host_key_checking = False' >> ansible.cfg

script:

  # run our role in the bootstrap play
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local

  # should test here