---

- hosts: all
  gather_facts: false
  vars:
  vars_files:
  - /etc/ansible/vars_files/whathood.yml
  tasks:
  - name: Setting whathood env var
    command: /bin/bash -c "echo 'WH_APP_ENV={{ item }}' >> /etc/environment"
    become: yes
    with_items: application_env

- hosts: all
  gather_facts: false
  vars:
  vars_files:
  - /etc/ansible/vars_files/whathood.yml
  roles:
    - role: whathood.clone_repo

- hosts: all
  gather_facts: false
  vars:
  vars_files:
  - /etc/ansible/vars_files/whathood.yml
  tasks:
  - name: compile coffeescript
    docker_container:
      name: "npm"
      image: quay.io/whathood/nodejs-bower-grunt
      volumes:
      - "{{ wh_src_dir }}:/data"
      cleanup: yes
      entrypoint: grunt coffee
    tags: [ coffee ]
    register: result
    become: yes

  - name: make sure the doctrine proxy dir is writeable
    file: path={{ wh_src_dir }}/app/data/DoctrineORMModule/Proxy mode=777 owner={{ansible_ssh_user}} state=directory
    become: yes
   
  - name: compile react
    command: docker run --rm -v {{ wh_src_dir }}/libs/react:/src -v {{ wh_src_dir }}/app/public/js/whathood:/build --name wh-jsx quay.io/whathood/jsx --extension jsx src build
    become: yes


  - name: copy in applicaton_env template
    template: src=application_env.j2 dest={{wh_src_dir}}/application_env

  - debug: var=wh_src_dir
    tags: [ ruby ]

  - name: install project ruby gems
    command: /home/ubuntu/.rvm/gems/ruby-2.3.1/wrappers/bundle install
    args:
      chdir: "{{wh_src_dir}}"
    tags: [ ruby, ruby-bundle ]
    environment:
      PATH: "/home/ubuntu/.rvm:{{ ansible_env.PATH }}"
