---

- hosts: all
  gather_facts: false
  vars_files:
  - /etc/ansible/vars_files/whathood.yml
  roles:
    - compile
    - role: composer
      tags: composer
    - role: less
      tags: less

    - bundler
    - { role: copy_code, from_dir: "{{ wh_src_dir }}", to_dir: "{{deploy_dest_dir}}" }
    - { role: "nginx", container_name: "nginx-{{ application_env }}", http_port: "81", app_dir: "{{ wh_src_dir }}" }
    - role: update_upstart
      tags: update_upstart
      sudo: yes

- hosts: all
  gather_facts: false
  include: system_check.yml
