---
# deploy.yml
#
# should:
# * prepare the docker environment
# * call the compile play
#
- hosts: all
  gather_facts: false
  vars:
    user: "{{ ansible_ssh_user }}"
  vars_files:
  - /etc/ansible/vars_files/whathood.yml
  roles:
    - role: prep_docker_env
      tags: prep_docker_env 
    - role: whathood.npm_setup
      tags: [ npm_install, npm_setup ]

- include: compile.yml

- hosts: all
  gather_facts: false
  vars:
    user: "{{ ansible_ssh_user }}"
  vars_files:
  - /etc/ansible/vars_files/whathood.yml
  roles:
    - role: prep_docker_env
      tags: prep_docker_env 
    - role: whathood.npm_setup
      tags: [ npm_install, npm_setup ]
    - compile
    - role: composer
      tags: composer
    - role: less
      tags: less

    - bundler

    - { role: copy_code, from_dir: "{{ wh_src_dir }}", to_dir: "{{deploy_dest_dir}}" }

    - { role: "nginx", container_name: "nginx-{{ application_env }}", http_port: "81", app_dir: "{{ wh_src_dir }}" }

    - role: update_upstart
      tags: update_upstart
      sudo: yes

    - role: system_check
      system_check_dir: "{{application_root}}"
      tags: system_check
