---

- hosts: all
  vars:
    user: "{{ ansible_ssh_user }}"
  vars_files:
  - /etc/ansible/vars_files/whathood.yml
  roles:
    - compile
    - composer
    - bundler
    - { role: copy_code, from_dir: "{{ deploy_working_dir}}", to_dir: "{{ production_working_dir}}" }
    - { role: "nginx", container_name: "nginx-{{ application_env }}", http_port: "8081", app_dir: "{{ deploy_working_dir }}" }

- include: update_upstart.yml

- include: system_check.yml
