---

- hosts: all
  gather_facts: false
  vars_files:
  - /etc/ansible/vars_files/whathood.yml
  roles:
    - compile
    - composer
    - bundler
    - { role: copy_code, from_dir: "{{ deploy_working_dir}}", to_dir: "{{ production_working_dir}}" }
    - { role: "nginx", container_name: "nginx-{{ application_env }}", http_port: "81", app_dir: "{{ deploy_working_dir }}" }
    - role: update_upstart
      tags: update_upstart
      sudo: yes

- hosts: all
  gather_facts: false
  include: system_check.yml
