---

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ssh_pub_key_material: "{{ lookup('env', 'WH_SSH_PUB_KEY_MATERIAL') }}"
  roles:
    -  whathood.ssh_pub_key_material_init
    -  jsmiley.provision_ec2

- include: setup.yml
