---

- hosts: all
  gather_facts: true
  vars:
    user: "{{ ansible_ssh_user }}"
    log_dir: /var/log/whathood
    dot_vim_dir: "/home/{{ansible_ssh_user}}/.vim"
  roles:

    - name: install node on guest
      role: nodesource.node
      sudo: yes
      tags: node

    - name: configure timezone
      role: timezone
      sudo: yes
      tags: timezone

    - name: install common stuff on the guest
      role: common
      tags: common
      sudo: yes

    # Set up docker on the target machine
    - { role: virt_host_docker,
        sudo: yes,
        vars: { user: user },
        docker_group_members: [ user ]
      }

    - name: configure vim
      role: jsmiley.vim
      tags: vim

- include: git.yml

- hosts: all
  gather_facts: false
  vars:
    user: "{{ ansible_ssh_user }}"
    log_dir: /var/log/whathood
  roles:
    - { role: rvm, sudo: yes }

- hosts: all
  gather_facts: false
  include: prep_docker_env.yml

- hosts: all
  gather_facts: false
  include: deploy.yml
  vars:
    skip_db_check: true
    skip_system_check: true

- hosts: all
  gather_facts: false
  roles:
  - { role: import_db }
  vars:
    nginx_container: "{{nginx_container_name}}"
  tags: import_db

- hosts: all
  include: system_check.yml
