---

- hosts: all
  gather_facts: true
  vars:
    user: "{{ ansible_ssh_user }}"
    log_dir: /var/log/whathood
    dot_vim_dir: "/home/{{ansible_ssh_user}}/.vim"
  roles:

    - name: install node on guest
      role: nodesource.node
      become: yes
      tags: node

- include: git.yml

- hosts: all
  gather_facts: false
  vars:
    user: "{{ ansible_ssh_user }}"
    log_dir: /var/log/whathood
  roles:
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.1'],
        rvm1_user: 'ubuntu'
      }
  become: yes

- hosts: all
  gather_facts: false
  vars:
    ansible_ssh_user: "{{ ansible_user }}"
  tags: [ "docker" ]
  roles:
  - angstwad.docker_ubuntu
  become: yes

- hosts: all
  gather_facts: false
  roles:
  - role: prep_docker_env
    vars:
      user: "{{ ansible_ssh_user }}"
    tags: prep_docker_env 

- include: deploy.yml
  vars:
    skip_db_check: true
    skip_system_check: true

- hosts: all
  gather_facts: false
  roles:
  - { role: import_db }
  vars:
    nginx_container: "{{nginx_container_name}}"
  tags: import_db
