---

- hosts: all
  vars:
    user: "{{ ansible_ssh_user }}"
    log_dir: /var/log/whathood
  roles:
    - { role: common, sudo: yes }
    # Set up docker on the target machine
    - { role: virt_host_docker,
        sudo: yes,
        vars: { user: user },
        docker_group_members: [ user ]
      }

    - { role: vim, sudo: yes }

- include: git.yml

- hosts: all
  vars:
    user: "{{ ansible_ssh_user }}"
    log_dir: /var/log/whathood
  roles:
    - { role: rvm, sudo: yes }

    - { role: setup }

    # get the docker images prepped
    - { role: prep_docker_env, sudo: yes }

- include: deploy.yml

- include: import_db.yml
  vars:
    nginx_container: "nginx-{{ application_env }}"

- hosts: all
  vars:
    user: "{{ ansible_ssh_user }}"
    log_dir: /var/log/whathood
  roles:
    - { role: import_db }
