---

# Gather facts about all ec2 instances
- ec2_remote_facts:
    region: "{{ region }}"
  register: ec2

- name: terminate instance with no 'Name' tag defined
  ec2:
    state: 'absent'
    region: "{{ region }}"
    instance_id: "{{ item.id }}" 
  when:  (item.tags.Name is undefined)
  with_items: "{{ ec2.instances }}"
