---

- set_fact:
    composer_cache_dir: "{{ wh_src_dir }}/.composer"
    composer_image: composer:1.9
    php_app_dir: "{{ wh_src_dir }}/app"
    
- name: run composer install via docker container
  docker_container:
    name: composer
    image: "{{ composer_image }}"
    command: composer global require hirak/prestissimo
    working_dir: /app
    volumes:
      - "{{ php_app_dir }}:/app"
      - "{{ composer_cache_dir }}:/tmp"
    auto_remove: yes
  tags: [ composer ]

- name: run composer install via docker container
  docker_container:
    name: composer
    image: "{{ composer_image }}"
    command: composer install
    working_dir: /app
    volumes:
      - "{{ php_app_dir }}:/app"
      - "{{ composer_cache_dir }}:/tmp"
    auto_remove: yes
  tags: [ composer ]
