---

- name: installing vendor libraries
  make:
    target: "composer-install"
    chdir: "{{ wh_src_dir }}"
  tags: [ composer ]

- name: composer creates an autoload classmap
  command: make composer-dumpautoload
  args:
    chdir: "{{ wh_src_dir }}"
  tags: [ composer ]
