---

- name: installing vendor libraries
  command: make composer-install
  args:
    chdir: /home/{{ansible_ssh_user}}/src/whathood

- name: composer creates an autoload classmap
  command: make composer-dumpautoload
  args:
    chdir: /home/{{ansible_ssh_user}}/src/whathood
  when: application_env == 'production'
