---

- name: ensuring no other docker containers
  docker:
    name: wh_composer
    image: "{{docker_composer_image}}"
    state: absent
  sudo: yes

- name: installing vendor libraries
  command: docker run -ti -v /home/{{ ansible_ssh_user }}/.composer:/root/.composer -v {{ wh_src_dir }}/app:/srv --name wh_composer {{ docker_composer_image }} install --no-interaction
  sudo: yes

- name: composer creates an autoload classmap
  command: sudo docker run -ti -v {{application_root}}/app:/srv {{ docker_composer_image }} dumpautoload -o
  when: application_env == 'production'
