---

- set_fact:
    composer_cache_dir: "{{ wh_src_dir }}/.composer"
    composer_image: whathood/composer
    php_app_dir: "{{ wh_src_dir }}/app"
    
- name: composer requires hirak/prestissimo cache-dir= [{{ composer_cache_dir }}]
  docker_container:
    name: composer
    image: "{{ composer_image }}"
    command: global require hirak/prestissimo
    working_dir: /app
    volumes:
      - "{{ php_app_dir }}:/app"
      - "{{ composer_cache_dir }}:/tmp"
    detach: no
  tags: [ composer ]

- name: composer install cache-dir= [{{ composer_cache_dir }}] php-app-dir= [{{ php_app_dir }}]
  docker_container:
    name: composer
    image: "{{ composer_image }}"
    command: install
    working_dir: /app
    volumes:
      - "{{ php_app_dir }}:/app"
      - "{{ composer_cache_dir }}:/tmp"
    detach: no
  tags: [ composer ]
