---

- name: installing vendor libraries
  make:
    target: "composer-install"
    chdir: "/home/{{ansible_user}}/src/whathood"
  tags: [ composer ]

- name: composer creates an autoload classmap
  command: make composer-dumpautoload
  args:
    chdir: /home/{{ansible_user}}/src/whathood
  tags: [ composer ]
