---

- name: run composer install via docker container
  docker_container:
    name: composer
    image: composer
    command: install
    volumes:
      - "{{ wh_src_dir }}/app:/app"
      - "/var/tmp/composer:/tmp"
  tags: [ composer ]

- name: run composer dumpautoload via docker container
  docker_container:
    name: composer
    image: composer
    command: dumpautoload
    volumes:
      - "{{ wh_src_dir }}/app:/app"
      - "/var/tmp/composer:/tmp"
  tags: [ composer ]
