---

# for ansible's url module used, by system check on urls
- pip: name=httplib2
  become: yes

- name: nginx is compressing
  shell: "curl -D - -H 'Accept-Encoding: gzip' {{uri_base}}  -o /dev/null 2>/dev/null | grep 'Content-Encoding: gzip' | wc | awk '{ print $1 }'"
  register: command_result
  failed_when: "'0' in command_result.stdout"
  when: not skip_system_check

- name: Checking for uri for a 404
  uri:
    url: "{{uri_base}}/api/v1/asdlfkasjdflsdf"
    status_code: 404
  when: not skip_system_check

- uri: url="{{item.uri}}"
  with_items:
  - uri: "{{uri_base}}"
  - uri: "{{uri_base}}/api/v1/neighborhood-border/region/Philadelphia"
  - uri: "{{uri_base}}/api/v1/point-election/x/-75.0898801428571/y/40.0218525714286"
  - uri: "{{uri_base}}/js/bundle.js"
  when: not skip_system_check

- name: wh-worker is running
  shell: status wh-worker
  register: command_result
  failed_when: "'waiting' in command_result.stdout"
  when: not skip_system_check and application_env == 'production'
