---

- name: remove any upstart scripts
  command: rm -rf /etc/init/wh-*
  become: true

- name: copy over current upstart scripts
  template: src={{item.file}} dest=/etc/init/{{item.dest}}
  become: yes
  with_items:
  - { file: wh-worker.conf.j2, dest: wh-worker.conf }
  - { file: wh-foreman.conf, dest: wh-foreman.conf }

- name: is wh-worker running
  command: status wh-worker
  become: yes
  register: result

- command: stop wh-worker
  become: true
  when: '"started" in result.stdout'

- name: is wh-foreman running
  command: status wh-foreman
  become: yes
  register: result

- command: stop wh-foreman
  become: true
  when: '"started" in result.stdout'

- name: copy over current upstart scripts
  template: src={{item.file}} dest=/etc/init/{{item.dest}}
  become: yes
  with_items:
  - { file: wh-worker.conf.j2, dest: wh-worker.conf }
  - { file: wh-foreman.conf, dest: wh-foreman.conf }

- name: start the upstart scripts
  command: start wh-worker
  become: yes
  when: application_env == "production"
