---

- name: remove any upstart scripts
  command: rm -rf /etc/init/wh-*
  sudo: true

- command: stop "{{ item.name }}"
  sudo: true
  ignore_errors: yes
  with_items:
  - { name: "wh-worker" }
  - { name: "wh-foreman" }

- name: copy over current upstart scripts
  template: src={{item.file}} dest=/etc/init/{{item.dest}}
  sudo: yes
  with_items:
  - { file: wh-worker.conf.j2, dest: wh-worker.conf }
  - { file: wh-foreman.conf, dest: wh-foreman.conf }

- name: start the upstart scripts
  command: start wh-worker
  sudo: yes
  when: application_env == "production"
